version: "3.8"

services:
  # Redis Message Queue
  redis:
    image: redis:7.2-alpine
    container_name: asterisk-ai-voice-agent-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

  # Call Controller Service
  call_controller:
    build:
      context: .
      dockerfile: services/call_controller/Dockerfile
    container_name: asterisk-ai-voice-agent-call-controller
    restart: always
    volumes:
      - ./shared:/app/shared
    depends_on:
      redis:
        condition: service_healthy
    network_mode: host
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - ASTERISK_HOST=127.0.0.1
      - REDIS_HOST=127.0.0.1
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}