version: "3.8"

services:
  # Redis Message Queue
  redis:
    image: redis:7.2-alpine
    container_name: asterisk-ai-voice-agent-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

  # Call Controller Service
  call_controller:
    build:
      context: .
      dockerfile: services/call_controller/Dockerfile
    container_name: asterisk-ai-voice-agent-call_controller
    # Expose the UDP port for RTP streams directly.
    # This maps port 8000 on the host to port 8000 in the container.
    ports:
      - "8000:8000/udp"
    volumes:
      - shared_audio:/shared/audio
      - shared_logs:/shared/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # The host IP is now required for Asterisk to send media back to this container
      - CONTAINER_HOST_IP=${CONTAINER_HOST_IP}
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  shared_audio:
  shared_logs: