version: '3.8'

services:
  ai-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_engine
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: "host"
    links:
      - local-ai-server

  local-ai-server:
    build:
      context: ./local_ai_server
      dockerfile: Dockerfile
    container_name: local_ai_server
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: "host"