version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  ai-voice-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-voice-agent
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./models:/app/models:ro
      - ./src:/app/src
      - ./config:/app/config
      - ./main.py:/app/main.py
      - ./test_piper.py:/app/test_piper.py
    depends_on:
      - redis
    restart: unless-stopped