version: '3.8'

services:
  asterisk-ai-voice-agent:
    build: .
    container_name: asterisk-ai-voice-agent
    network_mode: host
    environment:
      - INTEGRATION_MODE=sip
      - ASTERISK_HOST=voiprnd.nemtclouddispatch.com
      - ASTERISK_VERSION=16
      - SIP_EXTENSION=${SIP_EXTENSION:-1001}
      - SIP_PASSWORD=${SIP_PASSWORD:-password}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=info
      - VAD_ENABLED=true
      - NOISE_SUPPRESSION=true
      - ECHO_CANCELLATION=true
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
