version: '3.8'

services:
  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asterisk_ai_voice_agent
    
    # Volume mounts for instant code changes
    volumes:
      - ./models:/app/models  # Mount models directory
    
    # Environment variables
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    
    # Keep container running for development
    tty: true
    stdin_open: true
    
    # Restart policy
    restart: unless-stopped
    
    # Network mode for Asterisk communication
    network_mode: "host"