# Monolithic OpenAI Realtime Voice Agent configuration
# Requires OPENAI_API_KEY in .env

default_provider: "openai_realtime"
audio_transport: "audiosocket"
downstream_mode: "stream"

audiosocket:
  host: "0.0.0.0"
  port: 8090
  format: "ulaw"

barge_in:
  enabled: true
  initial_protection_ms: 200
  min_ms: 250
  energy_threshold: 1200
  cooldown_ms: 500
  post_tts_end_protection_ms: 100

streaming:
  sample_rate: 8000
  jitter_buffer_ms: 100
  keepalive_interval_ms: 5000
  connection_timeout_ms: 10000
  fallback_timeout_ms: 8000
  chunk_size_ms: 20
  min_start_ms: 300
  low_watermark_ms: 200
  provider_grace_ms: 500
  logging_level: "info"

providers:
  openai_realtime:
    enabled: true
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4o-realtime-preview-2024-12-17"
    voice: "alloy"
    base_url: "wss://api.openai.com/v1/realtime"
    instructions: "You are a concise voice assistant. Respond clearly and keep answers under 20 words unless more detail is requested."
    organization: ""
    input_encoding: "ulaw"
    input_sample_rate_hz: 8000
    provider_input_sample_rate_hz: 16000
    output_encoding: "linear16"
    output_sample_rate_hz: 24000
    target_encoding: "ulaw"
    target_sample_rate_hz: 8000
    response_modalities:
      - "audio"
      - "text"
    greeting: "${OPENAI_GREETING:-Hello, I am a Voice Assistant. How can I help you today?}"
    turn_detection:
      type: "server_vad"
      silence_duration_ms: 300
      threshold: 0.5
      prefix_padding_ms: 200

  local:
    enabled: false

llm:
  initial_greeting: "Hello I am an AI assistant for Jugaar LLC, How can I help you today?"
  prompt: "You are a concise and helpful voice assistant.Keep your answers under 20 words or less."
  model: "gpt-4o"
